import { Client } from "pg";

const sql = `
CREATE TABLE IF NOT EXISTS categories (
  category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT
);

CREATE TABLE IF NOT EXISTS producers  (
  producer_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  location TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS items (
  item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  model TEXT,
  category_id INTEGER,
  producer_id INTEGER,
  quantity INTEGER
);

ALTER TABLE items 
ADD CONSTRAINT fk_items_categories 
FOREIGN KEY (category_id) REFERENCES categories(category_id);

ALTER TABLE items 
ADD CONSTRAINT fk_items_producers 
FOREIGN KEY (producer_id) REFERENCES producers(producer_id);


INSERT INTO categories (category) 
VALUES 
('Strings'),
('Woodwinds'),
('Brass');

INSERT INTO producers (name, location, email) 
VALUES 
('Fender', 'Corona, California, USA', 'contact@fender.com'),
('Yamaha', 'Hamamatsu, Shizuoka, Japan', 'info@yamaha.co.jp'),
('Gibson', 'Nashville, Tennessee, USA', 'support@gibson.com'),
('Rikhi Ram', 'New Delhi, India', 'sales@rikhiram.in'),
('Buffet Crampon', 'Mantes-la-Ville, France', 'contact@buffet-crampon.com'),
('Selmer', 'Paris, France', 'info@selmer.fr'),
('Hohner', 'Trossingen, Germany', 'kontakt@hohner.de'),
('Bach', 'Elkhart, Indiana, USA', 'support@bachbrass.com'),
('Conn', 'Eastlake, Ohio, USA', 'info@conninstruments.com'),
('Besson', 'Charleville-Mézières, France', 'contact@besson-brass.fr');

INSERT INTO items (model, category_id, producer_id, quantity) 
VALUES 
('Stratocaster', 1, 1, 25),
('V3', 1, 2, 14),
('Mastertone', 1, 3, 8),
('Signature Sitar', 1, 4, 3),
('YFL-222', 2, 2, 19),
('R13', 2, 5, 12),
('Mark VI', 2, 6, 6),
('Marine Band', 2, 7, 40),
('YTR-8335', 3, 2, 17),
('42B', 3, 8, 9),
('8D', 3, 9, 5),
('Prestige', 3, 10, 4);
`;

const connectionString = process.argv[2] || process.env.PG_CONNECTION_STRING;

async function main() {
  const client = new Client({
    connectionString: connectionString,
  });
  client.connect();

  console.log("Populating db...");

  try {
    await client.query(sql);
    console.log("Populated");
  } catch (error) {
    console.log("Something went wrong");
    console.log(error);
  } finally {
    await client.end();
  }
}

main();
